### ISSUE TITLE
Podziękowanie oraz zapytanie

### ISSUE THREAD

**Issue by pablocool** [azman26/EPGazman#4]
Cześć

Dzięki za źródła EPG. Dzięki Tobie EPGImport nadal działa. Mam dwa pytania:
1. Skąd bierzesz te dane i jak generujesz pliki xml?
2. Czy wiesz może co się stało ze źródłami Rytec Poland?
Pozdrawiam

**Comment by 4meters** [comment]
Autor list nie odpowiedział, odpowiem za autora:
1. Listy brane są z tv.wp.pl i generowane za pomocą webgrabplus
2. Co do tego to nie wiem, nie zagłębiałem się w temat

**Comment by azman26** [comment]
1.  Dane wydarzeń pobierane są z wszelkich portali prezentujących ramówkę TV (WP, PolsatBox, Canal+, Teleman, itp.). Do grabowania i generowania plików xml używam WebGrab++

2.  Rytec Poland to teraz [azman] Poland XMLTV. Przejąłem od kolegi @doglover całą robotę w tworzeniu EPG dla polskich kanałów z SAT i dodałem od siebie IPTV, DVB-T oraz DVB-C tak aby 100% kanałów TV występujących na polskim rynku medialnym miało EPG

**Comment by azman26** [comment]
Obecnie jest tak
`<title>'title'{ - 'subtitle(, )'}</title>
	<desc>{[ 'category(, )' ] }{('episode(, )') }{'country(, )' }{'productiondate(, )' }{('rating(, )')}\n{FilmWeb: 'mdb-starrating(, )'  }{IMDB: 'starrating(, )'}{\n\n'description'}{\n\nReżyseria: 'director(, )'}{\nWystępują: 'actor(, )[max_elements=5]'}</desc>
	<sub-title />
	<credits />
	<date />
	<category />
	<country />
	<episode-num />
	<rating />
	<icon />
	<star-rating />
	<star-rating system="imdb" />`

Jest to specjalnie tak zorganizowane pod GUI E2 gdzie czy to w pierwszym infobar czy na liście wyboru kanałów dostajesz od razu pełne informacje o nadawanym programie oraz tytule odcinka.

` <programme start="20231204013000 +0100" stop="20231204022500 +0100" channel="Fox.pl">
    <title lang="pl">Kości 5 - Diabeł w szczegółach</title>
    <desc lang="pl">[ Serial Kryminalny ] (S5E14) USA 2009 (12+)
FilmWeb: 8.8/10  IMDB: 7.8/10

Ksiądz i ministrant przeżywają szok, gdy odkrywają w kościele płonące szczątki istoty z rogami. Booth i Brennan udają się na miejsce makabrycznego odkrycia. Dla Brennan religia to zabobon, ale kapłan, który znalazł szczątki, obawia się, że to emanacja zła. Booth i Brennan zabierają kości do laboratorium. Camille z powodu demonicznych skojarzeń jest tym przypadkiem poruszona. Arastoo Vaziri, asystent Brennan, który jest muzułmaninem, stwierdza, że ofiara jest człowiekiem, ale miała...ogon. Dalsze badania wykazują, że człowiek był rasy białej i miał około dwudziestu lat. Hodgins na podstawie analizy biochemicznej stwierdza, skąd pochodziły rogi. Natomiast Angela dokonuje rekonstrukcji twarzy demona i poznaje jego prawdziwą tożsamość. Wkrótce Brennan i Booth wybierają się z wizytą do rodziny ofiary.

Reżyseria: Ian Toynton
Występują: dr Temperance 'Bones' Brennan - Emily Deschanel, agent specjalny Seeley Booth - David Boreanaz, Angela Montenegro - Michaela Conlin, dr Jack Hodgins - T.J. Thyne, dr Camille Saroyan - Tamara Taylor</desc>
  </programme>`
